# Generated by Django 4.2.6 on 2023-11-24 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('disp_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_news',
            name='news_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
