# Generated by Django 4.2.6 on 2023-11-24 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disp_news', '0002_daily_news_news_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_news',
            name='news_img',
        ),
    ]
