# Generated by Django 4.2.6 on 2023-11-24 10:57

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disp_news', '0003_remove_daily_news_news_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_news',
            name='news_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='news_title', unique=True),
        ),
    ]
