# Generated by Django 4.2.6 on 2023-11-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disp_news', '0004_daily_news_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_news',
            name='news_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='news/'),
        ),
    ]
